name: neural-nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blosc=1.21.6=he440d0b_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_h2d575fe_109
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libcblas=3.11.0=4_h0358290_openblas
  - libcurl=8.17.0=h4e3cde8_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=4_h47877c9_openblas
  - libnetcdf=4.9.2=nompi_h00e09a9_116
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.5=h064dc61_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.10.0=h5888daf_1
  - ncurses=6.5=h7934f7d_0
  - openssl=3.6.0=h26f9b46_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - python_abi=3.8=2_cp38
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - snappy=1.2.2=h03e3b7b_1
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - boto3==1.17.112
      - botocore==1.20.112
      - brain-score==0.2
      - brainio-base==0.1.0
      - brainio-collection==0.1.0
      - cftime==1.4.1
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - cycler==0.12.1
      - dask==2023.2.0
      - exceptiongroup==1.3.1
      - filelock==3.16.1
      - fire==0.4.0
      - fsspec==2025.3.0
      - h5py==2.10.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - iniconfig==2.3.0
      - jmespath==0.10.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - locket==1.0.0
      - matplotlib==3.3.4
      - mkgu==0.1.0
      - netcdf4==1.5.7
      - nltk==3.5
      - nltk-contrib==3.5
      - numpy==1.19.5
      - packaging==25.0
      - pandas==1.2.5
      - partd==1.4.1
      - pillow==10.4.0
      - pluggy==1.6.0
      - protobuf==3.20.3
      - pygments==2.19.2
      - pyparsing==3.1.4
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.32.5
      - result-caching==0.1.0
      - s3transfer==0.4.2
      - sacremoses==0.1.1
      - scikit-learn==0.24.2
      - scipy==1.5.4
      - seaborn==0.11.1
      - six==1.17.0
      - tensorboardx==1.8
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tokenizers==0.10.3
      - tomli==2.3.0
      - toolz==1.0.0
      - torch==1.8.0
      - torchvision==0.9.0
      - tqdm==4.67.1
      - transformers==4.10.0
      - typing-extensions==4.13.2
      - urllib3==1.26.20
      - xarray==0.16.1
prefix: /home/horiaphilip/miniconda3/envs/neural-nlp
